apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
  labels:
    app: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: us-central1-docker.pkg.dev/zippy-tiger-473114-k3/demo-registry/container1
        ports:
        - containerPort: 5000

